spring:
  redis:
    host: 47.108.215.4
    # 连接超时时间（记得添加单位，Duration）
    timeout: 10000ms
    # Redis默认情况下有16个分片，这里配置具体使用的分片
#    # database: 0
#    lettuce:
#      pool:
#        # 连接池最大连接数（使用负值表示没有限制） 默认 8
#        max-active: 8
#        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
#        max-wait: -1ms
#        # 连接池中的最大空闲连接 默认 8
#        max-idle: 8
#        # 连接池中的最小空闲连接 默认 0
#        min-idle: 0
    password:
#  cache:
#    # 一般来说是不用配置的，Spring Cache 会根据依赖的包自行装配
#    type: redis
  cache:
    #The global expiration time, if missing, 30 minutes is default:
    defaultExpiration: 18050
    # Configuring each of specified keys of cache, unit: second:
    expirations:
      creditLine: 600
    #The configuration of redis server-side:
    redis:
      host: 47.108.215.4
      port: 6379
      password:
      database: 0
      lettuce:
        pool:
          min-idle: 5
          max-idle: 10
          max-active: 8
          max-wait: 1ms
        shutdown-timeout: 100ms
logging:
  level:
    com.xkcoding: debug
